### ISSUE TITLE
DEPRECATION: ember-cli-babel 5.x has been deprecated

### ISSUE THREAD

**Issue by rinoldsimon** [trentmwillis/ember-singularity-mixins#10]
After installing ember-singularity-mixins in an Ember project, following error appears when running the server:

> DEPRECATION:ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6.0

### Environment
Ember Version: 2.18.2
Ember CLI Version: 2.18.2
### Steps to Reproduce
In the Ember project install ember-singularity-mixins:

> ember install ember-singularity-mixins

After that run an Ember command like:

> ember -v

or:

> ember s

**Comment by trentmwillis** [comment]
Thanks, would you mind submitting a PR to upgrade?

**Comment by rinoldsimon** [comment]
PR has been made

**Comment by trentmwillis** [comment]
Fixed by https://github.com/trentmwillis/ember-singularity-mixins/pull/12.
