### ISSUE TITLE
`npm run test` gets stuck in ember beta scenario

### ISSUE THREAD

**Issue by ssutar** [trentmwillis/ember-singularity-mixins#9]
The execution becomes unresponsive after

`For scenario ember-beta, using:
Versions do not match: Expected: components/ember#beta but saw 3.0.0-beta.2-beta+b4135dfe This might be ok, depending on the scenario
  ember 3.0.0-beta.2-beta+b4135dfe
(node:11363) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
WARNING: Node v8.10.0 has currently not been tested against Ember CLI and may result in unexpected behaviour.
version: 1.13.14
Built project successfully. Stored in "/github/ember-singularity-mixins/tmp/class-tests_dist-uW7anUtn.tmp".`

Version info:
Node: v8.10.0
NPM: 5.7.1

**Comment by stefanpenner** [comment]
This is likely due to various dependencies being quite old. Such as ember-cli 1.x and testem.js using phantom not chrome.

**Comment by ssutar** [comment]
This is fixed now. Closing this ticket
